//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameTable
    {
        public int gameId { get; set; }
        public Nullable<bool> invalid { get; set; }
        public string gameMode { get; set; }
        public string gameType { get; set; }
        public string subType { get; set; }
        public Nullable<int> mapId { get; set; }
        public Nullable<int> teamId { get; set; }
        public Nullable<int> championId { get; set; }
        public Nullable<int> spell1 { get; set; }
        public Nullable<int> spell2 { get; set; }
        public Nullable<int> levelVal { get; set; }
        public Nullable<long> createDate { get; set; }
        public int summonerId { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> goldEarned { get; set; }
        public Nullable<int> numDeaths { get; set; }
        public Nullable<int> minionsKilled { get; set; }
        public Nullable<int> championsKilled { get; set; }
        public Nullable<int> goldSpent { get; set; }
        public Nullable<int> totalDamageDealt { get; set; }
        public Nullable<int> totalDamageTaken { get; set; }
        public Nullable<int> doubleKills { get; set; }
        public Nullable<int> tripleKills { get; set; }
        public Nullable<int> killingSprees { get; set; }
        public Nullable<int> largestKillingSpree { get; set; }
        public Nullable<int> team { get; set; }
        public Nullable<bool> win { get; set; }
        public Nullable<int> neutralMinionsKilled { get; set; }
        public Nullable<int> largestMultiKill { get; set; }
        public Nullable<int> physicalDamageDealtPlayer { get; set; }
        public Nullable<int> magicDamageDealtPlayer { get; set; }
        public Nullable<int> physicalDamageTaken { get; set; }
        public Nullable<int> magicDamageTaken { get; set; }
        public Nullable<int> timePlayed { get; set; }
        public Nullable<int> totalHeal { get; set; }
        public Nullable<int> totalUnitsHealed { get; set; }
        public Nullable<int> assists { get; set; }
        public Nullable<int> item0 { get; set; }
        public Nullable<int> item1 { get; set; }
        public Nullable<int> item2 { get; set; }
        public Nullable<int> item3 { get; set; }
        public Nullable<int> item4 { get; set; }
        public Nullable<int> item5 { get; set; }
        public Nullable<int> item6 { get; set; }
        public Nullable<int> sightWardsBought { get; set; }
        public Nullable<int> physicalDamageDealtToChampions { get; set; }
        public Nullable<int> totalDamageDealtToChampions { get; set; }
        public Nullable<int> trueDamageDealtPlayer { get; set; }
        public Nullable<int> trueDamageDealtToChampions { get; set; }
        public Nullable<int> trueDamageTaken { get; set; }
        public Nullable<int> wardPlaced { get; set; }
        public Nullable<int> neutralMinionsKilledEnemyJungle { get; set; }
        public Nullable<int> neutralMinionsKilledYourJungle { get; set; }
        public Nullable<int> totalTimeCrowdControlDealt { get; set; }
        public Nullable<int> barracksKilled { get; set; }
        public Nullable<int> turretsKilled { get; set; }
        public Nullable<int> largestCriticalStrike { get; set; }
        public Nullable<int> magicDamageDealtToChampions { get; set; }
        public Nullable<int> visionWardsBought { get; set; }
    }
}
